### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by mjlomeli** [max-arnold/markdown-tweetable#2]
```
File "lib\site-packages\flaskext\markdown.py", line 116, in register_extension
    instance = ext_cls()
TypeError: __init__() missing 2 required positional arguments: 'pattern' and 'config'
```

When trying to use TweetableExtension

**Comment by max-arnold** [comment]
You haven’t provided enough information for me to help you. Could you please provide a code snippet where you initialize the markdown library and configure the extension?

**Comment by max-arnold** [comment]
And also I need to know which version of python-markdown is used

**Comment by max-arnold** [comment]
Got no response in 3 months, closing this
